#!/usr/bin/perl
use strict;
use warnings;

# Process the table SID output from pyang.
# 1. Shorten SID column to 4 chars.
# 2. Abbreviate paths containing /ietf...:voucher/ to .../

while(<>) {
    chomp;

    # Skip metadata lines
    next if(/^File/);
    next if(/^Number/);
    next if(/^No .sid file/);
    next if(/WARNING/);
    next if(/^\s*$/);  # Matches empty lines or lines with only whitespace

    # 1. Handle Header Modification
    if (/^SID/) {
        # Print tighter header
        print "SID  Assigned to\n";
        next;
    }

    # 2. Handle Separator Modification
    if (/^---/) {
        # Print 4 dashes for SID, space, then the rest
        print "---- --------------------------------------------------\n";
        next;
    }

    # Split the line into 3 parts: SID, Type, and the Object/Path
    my ($sid, $type, $object) = split(' ', $_, 3);

    # Safety check if split didn't find enough columns
    next unless defined $object;

    # 3. Abbreviation Logic
    # We match "/ietf", followed by characters until ":voucher", followed by a slash.
    # This replaces "/ietf-voucher-request:voucher/" with ".../"
    # Note: This logic inherently skips the "first" entry (the module) because it has no slashes.
    # It also skips the root node (e.g. "...:voucher") because there is no trailing slash.
    $object =~ s{^/ietf.*?:voucher/}{.../};

    # 4. Output Formatting
    # %-4s : Left-align SID in 4 spaces
    # %-6s : Left-align Type (width of "module")
    # %s   : The object path
    printf("%-4s %-6s %s\n", $sid, $type, $object);
}