#!/usr/bin/perl

# process the table SID output from pyang and make it fit into 70 columns.
# do this by truncating the left-hand side of the third column, except for the module
# name, which is the first entry.
# first two columns are allocated 22 characters, so 70-22 = 48.

my $first = 1;

while(<ARGV>) {
    chomp;

    next if(/^File/);
    next if(/^Number/);
    next if(/^No .sid file/);
    next if(/module/);
    next if(/WARNING/);
    next if(/^$/);     # remove completely empty lines
    next if(/^\s+$/);  # remove lines with only spaces

    ($sid, $type, $object) = split;

    unless($first) {
    print STDERR "FIRST: $first\n";
        $object = substr($object, -48);
        # now actually align it on the /.
        $object =~ s,.*(/[^/]+),...\1,;
    }

    print sprintf("%9s %6s %s\n", $sid, $type, $object);
    $first = 0;
}


